" (c) 2012 Planet Earth
" 
" This vimrc is not meant to be compatible ever
" and is meant for running on trunk vim with trunk scripts
set nocompatible
" Pathogen is trunk too so we load it manually
runtime bundle/vim-pathogen/autoload/pathogen.vim
"call pathogen#runtime_append_all_bundles()
let g:pathogen_disabled = ["easygrep", "nerdcommenter", "vim-afterimage", "vim-abolish", "gundo", "vim-repeat", "vim-unimpaired"]
call pathogen#infect()

syntax on
filetype on
filetype indent on
filetype plugin on

set list listchars=tab:··,trail:·,extends:»
set backspace=indent,eol,start
set number
set smartindent autoindent
set tabstop=2
set shiftwidth=2
set expandtab
set wrap!
set directory=/tmp
set hidden
set incsearch
set ignorecase
set smartcase
set encoding=utf-8
set fileencoding=utf-8
"set statusline=%2*%n\|%<%*%-.40F%2*\|\ %2*%M\ %3*%=%1*\ %1*%2.6l%2*x%1*%1.9(%c%V%)%2*[%1*%P%2*]%1*%2B
"set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

set wildmenu
set wildignore=.svn,CVS,.git,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif

set lazyredraw                " don't redraw when don't have to
set more
set showmode
set showcmd
set history=200
set linebreak
"set cmdheight=2               " command line two lines high
set undolevels=1000           " 1000 undos
set updatecount=100           " switch every 100 chars
set complete=.,w,b,u,U,t,i,d  " do lots of scanning on tab completion
"set ttyfast                   " we have a fast terminal
set noerrorbells              " No error bells please
set vb t_vb=
set shell=bash
set autoread                  " watch for file changes
"set autochdir                 " change working dir to file dir

let g:EasyGrepHidden=1
let g:EasyGrepIgnoreCase=0
let g:EasyGrepRecursive=1
let NERDTreeShowHidden=1
let NERDTreeIgnore = ['\.pyc$', '\.pyo$']
let g:NERDTreeDirArrows=1
let g:NERDTreeMinimalUI=1
let g:syntastic_auto_loc_list=1

"set tags=tags;/

